#!/bin/bash
project_dir=$(dirname "${BASH_SOURCE[0]}")
echo $project_dir
cd "$project_dir" || exit

args=
for i in "$@"
do
    args+="$i "
done

if [ ${#@} -eq 0 ]; then
    ./gradlew :statsnode:startBisqApp
else
    ./gradlew :statsnode:startBisqApp --args \"\""$args"\"\"
fi
