systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000

# Makes Y/N user prompts more readable during installer packaging
org.gradle.console=plain

org.gradle.dependency.verification.console=verbose

releaseBuild.javaVersion=21.0.6
releaseBuild.javaVendor=Azul Systems, Inc.
releaseBuild.gradleVersion=8.9

# Consistent character set and locale across all builds.
systemProp.file.encoding=UTF-8
systemProp.user.language=en
systemProp.user.country=US
systemProp.user.variant=
