version: '2.1'

services:
    seednode:
        container_name: seednode
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/prod/Dockerfile
            args:
                SEEDNODE_URL: ${SEEDNODE_URL}
                SEEDNODE_BRANCH: ${SEEDNODE_BRANCH}
        image: seednode
        depends_on:
            - btcd
        ports:
            - 8000:8000
            - 9010:9010
            - 9011:9011
        expose:
            - 6969
            - 5120
        volumes:
            - ./local:${WORKING_DIR}
        environment:
            - GRADLE_USER_HOME=/home/gradle
            - ONION_ADDRESS=${ONION_ADDRESS}
            - MAX_MEMORY=1200
            - MAX_CONNECTIONS=30
            - BASE_CURRENCY_NETWORK=BTC_MAINNET
            - APP_NAME=${APP_NAME}
            - NODE_PORT=8000
            - DAO_ACTIVATED=true
            - FULL_DAO_NODE=true
            - RPC_HOST=btcd
            - RPC_PORT=8332
            - RPC_USER=${RPC_USER}
            - RPC_PASSWORD=${RPC_PASSWORD}
            - RPC_BLOCKNOTIFY_HOST=btcd
            - RPC_BLOCKNOTIFY_PORT=5120
        networks:
            bisq_net:
                ipv4_address: 172.28.1.3

    collectd:
        container_name: collectd
        restart: unless-stopped
        build:
            context: ./docker/prod
            dockerfile: Dockerfile-collectd
        image: collectd
        depends_on:
            - seednode
        networks:
            bisq_net:
                ipv4_address: 172.28.1.4

    btcd:
        build:
            context: .
            dockerfile: docker/prod/Dockerfile-btc
        image: bisq/btcd
        container_name: btcd
        restart: unless-stopped
        command:
            -printtoconsole
            -rpcport=8332
            -server=1
            -txindex=1
            -dbcache=1000
            -maxconnections=800
            -timeout=30000
            -listen=0
            -rpcuser=${RPC_USER}
            -rpcallowip=0.0.0.0/0
            -rpcbind=127.0.0.1
            -rpcbind=btcd
            -rpcpassword=${RPC_PASSWORD}
            -blocknotify="bash ~/.bitcoin/blocknotify %s"
        ports:
            - 8333:8333
            - 18443:18443
        volumes:
            - ./docker/prod/blocknotify:/home/bitcoin/.bitcoin/blocknotify
            - ${BTC_DATA_DIR}:/home/bitcoin/.bitcoin/
        networks:
            bisq_net:
                ipv4_address: 172.28.1.2

    nginx:
        image: nginx:latest
        container_name: collectd_nginx
#        context: ./docker
        volumes:
            - ./docker/prod/nginx.conf:/etc/nginx/nginx.conf
            - ./cert.crt:/etc/nginx/cert.crt
            - ./cert.key:/etc/nginx/cert.key
        depends_on:
            - collectd
        expose:
            - "2003"
        networks:
            bisq_net:
                ipv4_address: 172.28.1.5

# the network is needed because nginx can't resolve dns names in its .conf file, so we use hard-coded ip addresses.
networks:
    bisq_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/24
