version: '2.1'

services:
    seednode:
        container_name: seednode
        restart: unless-stopped
        env_file:
            - .env
        build:
            context: .
            dockerfile: docker/prod/Dockerfile
        image: seednode
        ports:
            - 8000:8000
            - 9010:9010
            - 9011:9011
        expose:
            - 5120
        networks:
          bisq_net:
            ipv4_address: 172.28.1.3
        volumes:
            - ./local:${WORKING_DIR}
        environment:
            - GRADLE_USER_HOME=/home/gradle
            - ONION_ADDRESS=${ONION_ADDRESS}
            - MAX_MEMORY=1200
            - MAX_CONNECTIONS=30
            - BASE_CURRENCY_NETWORK=BTC_MAINNET
            - APP_NAME=${APP_NAME}
            - NODE_PORT=8000
            - DAO_ACTIVATED=true
            - FULL_DAO_NODE=true
            - RPC_HOST=172.28.1.4
            - RPC_PORT=8332
            - RPC_USER=${RPC_USER}
            - RPC_PASSWORD=${RPC_PASSWORD}
            - RPC_BLOCKNOTIFY_PORT=5120

    bitcoin-core:
        build:
            context: .
            dockerfile: docker/prod/Dockerfile-btc
        image: bisq/bitcoin-core
        container_name: btcd
        restart: unless-stopped
        command:
            -printtoconsole
            -rpcport=8332
            -server=1
            -txindex=1
            -dbcache=1000
            -maxconnections=800
            -timeout=30000
            -listen=0
            -rpcuser=${RPC_USER}
            -rpcallowip=172.28.1.3
            -rpcpassword=${RPC_PASSWORD}
            -blocknotify="bash ~/.bitcoin/blocknotify %s"
        ports:
            - 8333:8333
            - 18443:18443
        networks:
          bisq_net:
            ipv4_address: 172.28.1.4
        # environment:
        #     - BITCOIN_DATA=${BTC_DATA_DIR}
        volumes:
            - ./docker/prod/blocknotify:/home/bitcoin/.bitcoin/blocknotify
            - ${BTC_DATA_DIR}:/home/bitcoin/.bitcoin/

networks:
  bisq_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

