/*
 * This file is part of Bisq.
 *
 * Bisq is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * Bisq is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Bisq. If not, see <http://www.gnu.org/licenses/>.
 */

package bisq.common.util;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

/**
 * Run this class with Java 11 to regenerate {@link LegacyHashMapJava11EntryOrder}.
 *
 * Example:
 * /Users/dev/Library/Java/JavaVirtualMachines/azul-11.0.22/Contents/Home/bin/java ...
 */
public final class LegacyHashMapJava11EntryOrderGenerator {
    private static final int BASE64_CHUNK_LENGTH = 120;

    private LegacyHashMapJava11EntryOrderGenerator() {
    }

    public static void main(String[] args) throws IOException {
        Map<String, Integer> map = new HashMap<>();
        LegacyHashMapMassiveRandomizedEntryOrderSupport.fillMassiveRandomizedMap(map);
        String source = generatedSource(LegacyHashMapMassiveRandomizedEntryOrderSupport.entryValueOrder(map));

        if (args.length == 0) {
            System.out.print(source);
        } else if (args.length == 1) {
            Files.write(Paths.get(args[0]), source.getBytes(StandardCharsets.UTF_8));
        } else {
            throw new IllegalArgumentException("Usage: LegacyHashMapJava11EntryOrderGenerator [output-file]");
        }
    }

    private static String generatedSource(int[] entryValueOrder) {
        String base64Order = Base64.getEncoder().encodeToString(toBytes(entryValueOrder));
        StringBuilder builder = new StringBuilder(base64Order.length() + 3_000);

        builder.append("/*\n");
        builder.append(" * This file is generated by LegacyHashMapJava11EntryOrderGenerator.\n");
        builder.append(" * Regenerate it with Java 11, not the current project runtime.\n");
        builder.append(" */\n");
        builder.append('\n');
        builder.append("package bisq.common.util;\n");
        builder.append('\n');
        builder.append("import java.nio.ByteBuffer;\n");
        builder.append("import java.nio.ByteOrder;\n");
        builder.append("import java.util.Base64;\n");
        builder.append('\n');
        builder.append("final class LegacyHashMapJava11EntryOrder {\n");
        builder.append("    static final int ENTRY_COUNT = ")
                .append(LegacyHashMapMassiveRandomizedEntryOrderSupport.ENTRY_COUNT)
                .append(";\n");
        builder.append('\n');
        builder.append("    private static final int[] MASSIVE_RANDOMIZED_ENTRY_VALUE_ORDER = decodeIntArray(\n");
        builder.append("            new String[]{\n");
        for (int offset = 0; offset < base64Order.length(); offset += BASE64_CHUNK_LENGTH) {
            int end = Math.min(offset + BASE64_CHUNK_LENGTH, base64Order.length());
            builder.append("                    \"")
                    .append(base64Order, offset, end)
                    .append('"');
            if (end < base64Order.length()) {
                builder.append(',');
            }
            builder.append('\n');
        }
        builder.append("            });\n");
        builder.append('\n');
        builder.append("    private LegacyHashMapJava11EntryOrder() {\n");
        builder.append("    }\n");
        builder.append('\n');
        builder.append("    static int[] massiveRandomizedEntryValueOrder() {\n");
        builder.append("        return MASSIVE_RANDOMIZED_ENTRY_VALUE_ORDER.clone();\n");
        builder.append("    }\n");
        builder.append('\n');
        builder.append("    private static int[] decodeIntArray(String[] chunks) {\n");
        builder.append("        StringBuilder builder = new StringBuilder();\n");
        builder.append("        for (String chunk : chunks) {\n");
        builder.append("            builder.append(chunk);\n");
        builder.append("        }\n");
        builder.append("        byte[] bytes = Base64.getDecoder().decode(builder.toString());\n");
        builder.append("        if (bytes.length % Integer.BYTES != 0) {\n");
        builder.append("            throw new IllegalStateException(\"Invalid Java 11 entry order byte length: \" + bytes.length);\n");
        builder.append("        }\n");
        builder.append("        ByteBuffer buffer = ByteBuffer.wrap(bytes).order(ByteOrder.BIG_ENDIAN);\n");
        builder.append("        int[] values = new int[bytes.length / Integer.BYTES];\n");
        builder.append("        for (int i = 0; i < values.length; i++) {\n");
        builder.append("            values[i] = buffer.getInt();\n");
        builder.append("        }\n");
        builder.append("        if (values.length != ENTRY_COUNT) {\n");
        builder.append("            throw new IllegalStateException(\"Invalid Java 11 entry order size: \" + values.length);\n");
        builder.append("        }\n");
        builder.append("        return values;\n");
        builder.append("    }\n");
        builder.append("}\n");
        return builder.toString();
    }

    private static byte[] toBytes(int[] values) {
        ByteBuffer buffer = ByteBuffer.allocate(values.length * Integer.BYTES).order(ByteOrder.BIG_ENDIAN);
        for (int value : values) {
            buffer.putInt(value);
        }
        return buffer.array();
    }
}
