/*
 * This file is part of Bisq.
 *
 * Bisq is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * Bisq is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Bisq. If not, see <http://www.gnu.org/licenses/>.
 */

package bisq.common.util;

import bisq.common.util.LegacyHashMapJava11VectorSupport.Vector;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Run this class with Java 11 to regenerate {@link LegacyHashMapJava11Vectors}.
 *
 * Example:
 * /Users/dev/Library/Java/JavaVirtualMachines/azul-11.0.22/Contents/Home/bin/java ...
 */
public final class LegacyHashMapJava11VectorGenerator {
    private LegacyHashMapJava11VectorGenerator() {
    }

    public static void main(String[] args) {
        List<Vector> vectors = LegacyHashMapJava11VectorSupport.vectorDefinitionsWithoutExpectedHashes();

        System.out.println("/*");
        System.out.println(" * This file is generated by LegacyHashMapJava11VectorGenerator.");
        System.out.println(" * Regenerate it with Java 11, not the current project runtime.");
        System.out.println(" */");
        System.out.println();
        System.out.println("package bisq.common.util;");
        System.out.println();
        System.out.println("import java.util.Arrays;");
        System.out.println("import java.util.List;");
        System.out.println();
        System.out.println("import bisq.common.util.LegacyHashMapJava11VectorSupport.BuildMode;");
        System.out.println("import bisq.common.util.LegacyHashMapJava11VectorSupport.KeySetId;");
        System.out.println("import bisq.common.util.LegacyHashMapJava11VectorSupport.Vector;");
        System.out.println();
        System.out.println("final class LegacyHashMapJava11Vectors {");
        System.out.println("    private LegacyHashMapJava11Vectors() {");
        System.out.println("    }");
        System.out.println();
        System.out.println("    static final List<Vector> VECTORS = Arrays.asList(");
        for (int i = 0; i < vectors.size(); i++) {
            Vector vector = vectors.get(i);
            Map<String, Integer> map = LegacyHashMapJava11VectorSupport.buildMap(
                    vector,
                    HashMap::new,
                    HashMap::new);
            String digest = LegacyHashMapJava11VectorSupport.keyOrderDigest(map);
            String suffix = i == vectors.size() - 1 ? "" : ",";
            System.out.printf("            new Vector(\"%s\", KeySetId.%s, BuildMode.%s, %d, \"%s\")%s%n",
                    vector.name,
                    vector.keySetId.name(),
                    vector.buildMode.name(),
                    map.size(),
                    digest,
                    suffix);
        }
        System.out.println("    );");
        System.out.println("}");
    }
}
