/*
 * This file is generated by LegacyHashMapJava11VectorGenerator.
 * Regenerate it with Java 11, not the current project runtime.
 */

package bisq.common.util;

import java.util.Arrays;
import java.util.List;

import bisq.common.util.LegacyHashMapJava11VectorSupport.BuildMode;
import bisq.common.util.LegacyHashMapJava11VectorSupport.KeySetId;
import bisq.common.util.LegacyHashMapJava11VectorSupport.Vector;

final class LegacyHashMapJava11Vectors {
    private LegacyHashMapJava11Vectors() {
    }

    static final List<Vector> VECTORS = Arrays.asList(
            new Vector("empty_direct_put", KeySetId.EMPTY, BuildMode.DIRECT_PUT, 0,
                    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
            new Vector("null_and_edge_strings_direct_put", KeySetId.NULL_AND_EDGE_STRINGS, BuildMode.DIRECT_PUT, 14,
                    "72dc9035f2c18251996dc6206858eda442559158a0104929cb3a5b8f51778ddb"),
            new Vector("small_copy_constructor_jdk19_divergence", KeySetId.JDK19_COPY_DIVERGENCE_12,
                    BuildMode.COPY_FROM_LINKED_HASH_MAP, 12,
                    "3bfb7cac73e2f96b7ddd1bdcc4dba86a58b0cc21227402d86ba006dfd2f47870"),
            new Vector("sorted_k40_direct_put", KeySetId.K40, BuildMode.DIRECT_PUT, 40,
                    "b36ee3f86565e0c94298b5b7adb4fc656fe61599f9ddf8b0471231de2a8f1119"),
            new Vector("sorted_k40_copy_from_tree_map", KeySetId.K40, BuildMode.COPY_FROM_TREE_MAP, 40,
                    "b36ee3f86565e0c94298b5b7adb4fc656fe61599f9ddf8b0471231de2a8f1119"),
            new Vector("tx_output_k40_collectors_merge", KeySetId.TX_OUTPUT_K40,
                    BuildMode.COLLECTORS_TO_MAP_MERGE, 40,
                    "2a60fbe102f6bae5a927d46b01af8c83e5dd9c2109b49663c7c469a968dd7ea5"),
            new Vector("colliding_strings_8_list_bin", KeySetId.COLLIDING_STRINGS_8, BuildMode.DIRECT_PUT, 8,
                    "39de10e7a09e3aedd439345ef387788b7cda30f428230baaf200c2bd1282a7d5"),
            new Vector("colliding_strings_16_tree_bin", KeySetId.COLLIDING_STRINGS_16, BuildMode.DIRECT_PUT, 16,
                    "68b3446b44c2ab82dd61b30b01377d3e52f71ab42548ce876b990951af51f6e1"),
            new Vector("colliding_strings_64_tree_bin", KeySetId.COLLIDING_STRINGS_64, BuildMode.DIRECT_PUT, 64,
                    "6a3b0201dcabe2faf2b015d6ad023cd037526f58a14e9f45a0ad6b52f6bc8893"),
            new Vector("colliding_strings_128_tree_bin_splits", KeySetId.COLLIDING_STRINGS_WITH_SPLITS_128,
                    BuildMode.DIRECT_PUT, 128,
                    "681ad9108dbf25aa03a0f4dc77444bce9c7dfc958694558e7927d7503ba152c0"),
            new Vector("random_tx_output_2k_direct_put", KeySetId.RANDOM_TX_OUTPUT_2K, BuildMode.DIRECT_PUT, 2000,
                    "f4ecbe6a6fd91c68de4b9d1f7da15d71de4cf5a9024f686a749fa22ac4b18a52"),
            new Vector("random_tx_output_50k_direct_put", KeySetId.RANDOM_TX_OUTPUT_50K,
                    BuildMode.DIRECT_PUT, 50000,
                    "fda9e1f41428c9cb92ca941185870c00432ce2b18e5de9884da4628f3baa0195"),
            new Vector("duplicate_k40_collectors_merge_keep_first", KeySetId.DUPLICATE_K40,
                    BuildMode.COLLECTORS_TO_MAP_MERGE, 40,
                    "300bd38c3f25f5fd8aea1705fad1d70b7634b19dcdc46bc7b270472988b76196"),
            new Vector("random_tx_output_2k_mutate", KeySetId.RANDOM_TX_OUTPUT_2K,
                    BuildMode.PUT_UPDATE_REMOVE_REINSERT, 2000,
                    "590b9f719fcd4bf192f7a41276a14b6c719e2f7f80d9c72b164ba9381af35ce2"),
            new Vector("colliding_strings_64_tree_bin_mutate", KeySetId.COLLIDING_STRINGS_64,
                    BuildMode.TREE_BIN_REMOVE_REINSERT, 60,
                    "8c3b32d5cf5316c0935bfbd3da2a53a13d64b7c6a0b64cbc8940275681f7f77c")
    );
}
