FROM ubuntu:bionic

RUN apt-get update && apt-get install -y \
  collectd-core \
  openjdk-11-jre
COPY collectd.conf /etc/collectd/collectd.conf
COPY openjdk.conf /etc/ld.so.conf.d/openjdk.conf
#RUN systemctl --now enable collectd
CMD /bin/bash -c "trap : TERM INT; sleep infinity & wait"
#CMD /usr/sbin/collectd
