FROM nginx:1.17.3-alpine

COPY cert.key /etc/nginx/cert.key
COPY cert.crt /etc/nginx/cert.crt
COPY ./docker/prod/nginx.conf /etc/nginx/nginx.conf
RUN chown nginx:nginx /etc/nginx/cert*
CMD ["nginx", "-g", "daemon off;"]

