package io.bitsquare.msg;

public enum TradeMessageType
{
    REQUEST_TAKE_OFFER,
    ACCEPT_TAKE_OFFER_REQUEST,
    REJECT_TAKE_OFFER_REQUEST,
    TAKE_OFFER_FEE_PAYED,
    REQUEST_TAKER_DEPOSIT_PAYMENT,
    REQUEST_OFFERER_DEPOSIT_PUBLICATION,
    DEPOSIT_TX_PUBLISHED,
    BANK_TX_INITED
}
