name: Codacy Coverage Reporter

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-24.04
        name: codacy-coverage-reporter
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  submodules: 'true'
                  persist-credentials: false

            - name: Set up JDK
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
              with:
                  java-version: '21.0.6'
                  distribution: 'zulu'
                  check-latest: false

            - name: Build with Gradle
              uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
              with:
                  arguments: build jacocoTestReport testCodeCoverageReport --scan

            - name: Run codacy-coverage-reporter
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
              with:
                  project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                  coverage-reports: ${{ github.workspace }}/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
