name: Codacy Coverage Reporter

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-24.04
        name: codacy-coverage-reporter
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  submodules: 'true'
                  persist-credentials: false

            - name: Set up JDK
              uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
              with:
                  java-version: '21.0.6'
                  distribution: 'zulu'
                  check-latest: false

            - name: Build with Gradle
              uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
              with:
                  arguments: build jacocoTestReport testCodeCoverageReport --scan

            - name: Run codacy-coverage-reporter
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
              with:
                  project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                  coverage-reports: ${{ github.workspace }}/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
